"""
SENTINEL CORE - AUTOMATED REPORT GENERATOR (MALTEGO-STYLE)
Generates comprehensive, classified-grade reports in multiple formats (PDF, HTML, STIX, JSON).
Includes executive summaries, technical annexes, and visual graph exports.
"""
import json
import os
from datetime import datetime
from typing import Dict, List, Any
from collections import defaultdict

class ReportGenerator:
    def __init__(self):
        self.templates_path = "templates"
        os.makedirs(self.templates_path, exist_ok=True)

    def generate_executive_summary(self, case_data: Dict) -> str:
        """Generate high-level executive summary for leadership"""
        entities = case_data.get("entities", [])
        relationships = case_data.get("relationships", [])
        vulnerabilities = [e for e in entities if e.get("type") == "VULNERABILITY"]
        
        # Calculate risk score
        critical_vulns = len([v for v in vulnerabilities if v.get("meta", {}).get("severity") == "critical"])
        high_vulns = len([v for v in vulnerabilities if v.get("meta", {}).get("severity") == "high"])
        risk_score = min(100, (critical_vulns * 25) + (high_vulns * 10) + (len(entities) // 10))
        
        risk_level = "CRITICAL" if risk_score > 75 else "HIGH" if risk_score > 50 else "MEDIUM" if risk_score > 25 else "LOW"
        
        summary = f"""
# EXECUTIVE SUMMARY
**Case ID:** {case_data.get('id', 'N/A')}
**Target:** {case_data.get('target', 'N/A')}
**Generated:** {datetime.utcnow().isoformat()}
**Classification:** INTERNAL USE ONLY

## RISK ASSESSMENT
- **Overall Risk Score:** {risk_score}/100
- **Risk Level:** {risk_level}
- **Critical Vulnerabilities:** {critical_vulns}
- **High Severity Vulnerabilities:** {high_vulns}

## KEY FINDINGS
- Total Entities Discovered: {len(entities)}
- Infrastructure Relationships Mapped: {len(relationships)}
- Attack Surface Coverage: {'COMPREHENSIVE' if len(entities) > 50 else 'PARTIAL'}

## IMMEDIATE ACTIONS REQUIRED
{self._generate_recommendations(critical_vulns, high_vulns, entities)}

## INTELLIGENCE CONFIDENCE
- Data Sources: {len(set(e.get('source') for e in entities))}
- Average Confidence Score: {sum(e.get('confidence', 0) for e in entities) // max(len(entities), 1)}%

---
*This report was automatically generated by Sentinel Core Intelligence Platform*
"""
        return summary

    def _generate_recommendations(self, critical: int, high: int, entities: List) -> str:
        recs = []
        if critical > 0:
            recs.append("1. **IMMEDIATE**: Patch or mitigate {0} critical vulnerabilities within 24 hours".format(critical))
        if high > 0:
            recs.append("2. **URGENT**: Schedule remediation for {0} high-severity issues within 7 days".format(high))
        
        # Check for exposed services
        ips = [e for e in entities if e.get("type") == "IP"]
        if len(ips) > 5:
            recs.append("3. **REVIEW**: Large IP footprint detected ({0} IPs). Verify necessity of exposed assets.".format(len(ips)))
        
        # Check for subdomains
        domains = [e for e in entities if e.get("type") == "DOMAIN"]
        if len(domains) > 20:
            recs.append("4. **AUDIT**: Extensive subdomain presence ({0} domains). Review for shadow IT or forgotten assets.".format(len(domains)))
        
        if not recs:
            recs.append("1. Continue monitoring. No immediate critical actions identified.")
        
        return "\n".join(recs)

    def generate_technical_annex(self, case_data: Dict) -> str:
        """Generate detailed technical findings for engineers"""
        entities = case_data.get("entities", [])
        
        # Group by type
        by_type = defaultdict(list)
        for entity in entities:
            by_type[entity.get("type", "UNKNOWN")].append(entity)
        
        annex = f"""
# TECHNICAL ANNEX
**Case:** {case_data.get('id', 'N/A')}
**Generated:** {datetime.utcnow().isoformat()}

## ENTITY INVENTORY

"""
        for etype, items in sorted(by_type.items()):
            annex += f"### {etype} ({len(items)} found)\n\n"
            annex += "| Value | Confidence | Source | Metadata |\n"
            annex += "|-------|------------|--------|----------|\n"
            for item in items[:50]:  # Limit to top 50 per type
                meta_str = json.dumps(item.get("meta", {}))[:50] + "..." if len(json.dumps(item.get("meta", {}))) > 50 else json.dumps(item.get("meta", {}))
                annex += f"| {item.get('value', 'N/A')} | {item.get('confidence', 0)}% | {item.get('source', 'N/A')} | {meta_str} |\n"
            
            if len(items) > 50:
                annex += f"\n*...and {len(items) - 50} more {etype} entities omitted for brevity...*\n"
            
            annex += "\n\n"
        
        # Add relationship table
        relationships = case_data.get("relationships", [])
        if relationships:
            annex += "## RELATIONSHIP MAP\n\n"
            annex += "| Source | Type | Target | Confidence |\n"
            annex += "|--------|------|--------|------------|\n"
            for rel in relationships[:100]:
                annex += f"| {rel.get('source', 'N/A')} | {rel.get('type', 'RELATED')} | {rel.get('target', 'N/A')} | {rel.get('confidence', 0)}% |\n"
        
        return annex

    def generate_stix_export(self, case_data: Dict) -> Dict:
        """Export to STIX 2.1 format for threat intelligence sharing"""
        from uuid import uuid4
        
        stix_bundle = {
            "type": "bundle",
            "id": f"bundle--{uuid4()}",
            "objects": []
        }
        
        # Create identity (organization)
        org_identity = {
            "type": "identity",
            "id": f"identity--{uuid4()}",
            "created": datetime.utcnow().isoformat(),
            "modified": datetime.utcnow().isoformat(),
            "name": "Sentinel Core Analysis",
            "identity_class": "system"
        }
        stix_bundle["objects"].append(org_identity)
        
        # Convert entities to STIX observables/indicators
        entities = case_data.get("entities", [])
        for entity in entities:
            etype = entity.get("type", "").upper()
            value = entity.get("value", "")
            
            stix_obj = None
            
            if etype == "IP":
                stix_obj = {
                    "type": "ipv4-addr",
                    "id": f"ipv4-addr--{uuid4()}",
                    "value": value
                }
            elif etype == "DOMAIN":
                stix_obj = {
                    "type": "domain-name",
                    "id": f"domain-name--{uuid4()}",
                    "value": value
                }
            elif etype == "EMAIL":
                stix_obj = {
                    "type": "email-addr",
                    "id": f"email-addr--{uuid4()}",
                    "value": value
                }
            elif etype == "VULNERABILITY":
                cve_id = value if value.startswith("CVE-") else f"CVE-{value}"
                stix_obj = {
                    "type": "vulnerability",
                    "id": f"vulnerability--{uuid4()}",
                    "name": cve_id,
                    "description": entity.get("meta", {}).get("severity", "Unknown severity")
                }
            elif etype == "URL":
                stix_obj = {
                    "type": "url",
                    "id": f"url--{uuid4()}",
                    "value": value
                }
            
            if stix_obj:
                # Add confidence if available
                if entity.get("confidence"):
                    stix_obj["confidence"] = entity.get("confidence")
                
                # Add labels
                stix_obj["labels"] = [f"source:{entity.get('source', 'unknown')}"]
                
                stix_bundle["objects"].append(stix_obj)
        
        return stix_bundle

    def generate_html_report(self, case_data: Dict, include_graph: bool = True) -> str:
        """Generate interactive HTML report with embedded graphs"""
        
        # Simple embedded CSS/JS for standalone HTML
        html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sentinel Core Report - {case_data.get('id', 'CASE')}</title>
    <script src="https://cdn.jsdelivr.net/npm/vis-network@9.1.2/dist/vis-network.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/vis-network@9.1.2/styles/vis-network.min.css" rel="stylesheet" />
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 20px; background: #1a1a2e; color: #eee; }}
        .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 10px; margin-bottom: 20px; }}
        .card {{ background: #16213e; border-radius: 8px; padding: 20px; margin-bottom: 20px; box-shadow: 0 4px 6px rgba(0,0,0,0.3); }}
        .metric {{ display: inline-block; margin: 10px 20px; text-align: center; }}
        .metric-value {{ font-size: 2.5em; font-weight: bold; color: #667eea; }}
        .metric-label {{ font-size: 0.9em; opacity: 0.8; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 15px; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #2a2a4a; }}
        th {{ background: #0f3460; color: #667eea; }}
        tr:hover {{ background: #1f4068; }}
        #network {{ height: 600px; border: 1px solid #444; border-radius: 8px; }}
        .badge {{ padding: 4px 8px; border-radius: 4px; font-size: 0.8em; font-weight: bold; }}
        .badge-critical {{ background: #e74c3c; color: white; }}
        .badge-high {{ background: #e67e22; color: white; }}
        .badge-medium {{ background: #f1c40f; color: black; }}
        .badge-low {{ background: #27ae60; color: white; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🛡️ SENTINEL CORE INTELLIGENCE REPORT</h1>
        <p><strong>Case ID:</strong> {case_data.get('id', 'N/A')} | <strong>Target:</strong> {case_data.get('target', 'N/A')}</p>
        <p><strong>Generated:</strong> {datetime.utcnow().isoformat()} UTC</p>
        
        <div class="metrics">
            <div class="metric">
                <div class="metric-value">{len(case_data.get('entities', []))}</div>
                <div class="metric-label">Entities</div>
            </div>
            <div class="metric">
                <div class="metric-value">{len(case_data.get('relationships', []))}</div>
                <div class="metric-label">Relationships</div>
            </div>
            <div class="metric">
                <div class="metric-value">{len([e for e in case_data.get('entities', []) if e.get('type')=='VULNERABILITY'])}</div>
                <div class="metric-label">Vulnerabilities</div>
            </div>
            <div class="metric">
                <div class="metric-value">{len(set(e.get('source') for e in case_data.get('entities', [])))}</div>
                <div class="metric-label">Data Sources</div>
            </div>
        </div>
    </div>

    <div class="card">
        <h2>📊 Network Visualization</h2>
        <div id="network"></div>
    </div>

    <div class="card">
        <h2>🏷️ Entity Inventory</h2>
        <table>
            <thead>
                <tr>
                    <th>Type</th>
                    <th>Value</th>
                    <th>Confidence</th>
                    <th>Source</th>
                    <th>Severity</th>
                </tr>
            </thead>
            <tbody>
"""
        
        for entity in case_data.get("entities", [])[:100]:
            severity = entity.get("meta", {}).get("severity", "")
            severity_badge = f'<span class="badge badge-{severity.lower()}">{severity.upper()}</span>' if severity else '-'
            conf_class = "badge-critical" if entity.get("confidence", 0) < 50 else "badge-medium" if entity.get("confidence", 0) < 80 else "badge-low"
            
            html += f"""
                <tr>
                    <td><strong>{entity.get('type', 'UNKNOWN')}</strong></td>
                    <td style="font-family:monospace;">{entity.get('value', 'N/A')}</td>
                    <td><span class="badge {conf_class}">{entity.get('confidence', 0)}%</span></td>
                    <td>{entity.get('source', 'N/A')}</td>
                    <td>{severity_badge}</td>
                </tr>
"""
        
        html += """
            </tbody>
        </table>
    </div>

    <script>
        // Network Graph Data
        const nodes = new vis.DataSet([
"""
        
        # Add nodes
        entities = case_data.get("entities", [])
        for i, entity in enumerate(entities[:200]):  # Limit for performance
            node_color = "#667eea"
            if entity.get("type") == "IP": node_color = "#e74c3c"
            elif entity.get("type") == "DOMAIN": node_color = "#3498db"
            elif entity.get("type") == "VULNERABILITY": node_color = "#e67e22"
            elif entity.get("type") == "EMAIL": node_color = "#9b59b6"
            
            html += f'{{id: {i}, label: "{entity.get("value", "")[:20]}...", group: "{entity.get("type", "UNKNOWN")}", color: "{node_color}"}},\n'
        
        html += """
        ]);
        
        const edges = new vis.DataSet([
"""
        
        # Add edges
        relationships = case_data.get("relationships", [])
        entity_map = {e.get("value"): i for i, e in enumerate(entities[:200])}
        
        for rel in relationships[:300]:
            src_idx = entity_map.get(rel.get("source"), -1)
            tgt_idx = entity_map.get(rel.get("target"), -1)
            if src_idx >= 0 and tgt_idx >= 0:
                html += f'{{from: {src_idx}, to: {tgt_idx}, label: "{rel.get("type", "RELATED")}", arrows: "to"}},\n'
        
        html += """
        ]);
        
        // Initialize Network
        const container = document.getElementById('network');
        const data = { nodes: nodes, edges: edges };
        const options = {
            nodes: {
                shape: 'dot',
                size: 16,
                font: { size: 14, color: '#ffffff' },
                borderWidth: 2
            },
            edges: {
                width: 2,
                color: { inherit: 'from', opacity: 0.5 },
                smooth: { type: 'continuous' }
            },
            groups: {
                useDefaultGroups: false
            },
            physics: {
                stabilization: false,
                barnesHut: { gravitationalConstant: -3000, springConstant: 0.04 }
            },
            interaction: { hover: true, tooltipDelay: 200 }
        };
        
        const network = new vis.Network(container, data, options);
        
        network.on("click", function (params) {
            if (params.nodes.length > 0) {
                const nodeId = params.nodes[0];
                const node = nodes.get(nodeId);
                alert("Entity: " + node.label + "\\nType: " + node.group);
            }
        });
    </script>
</body>
</html>
"""
        return html

    def save_report(self, case_data: Dict, format: str = "html") -> str:
        """Save report to file"""
        timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        case_id = case_data.get("id", "case").replace(" ", "_")
        
        if format == "html":
            content = self.generate_html_report(case_data)
            filename = f"{case_id}_report_{timestamp}.html"
        elif format == "json":
            content = json.dumps(case_data, indent=2)
            filename = f"{case_id}_data_{timestamp}.json"
        elif format == "stix":
            content = json.dumps(self.generate_stix_export(case_data), indent=2)
            filename = f"{case_id}_stix_{timestamp}.json"
        else:
            raise ValueError(f"Unsupported format: {format}")
        
        filepath = os.path.join(self.templates_path, filename)
        with open(filepath, "w") as f:
            f.write(content)
        
        return filepath

# Singleton
generator = ReportGenerator()
